development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
